### ISSUE TITLE
Error importing io-ts package and warning critical dependency [webpack]

### ISSUE THREAD

**Issue by jefrydco** [holvonix-open/solr-query-io-ts#25]
**NOTE: By submitting this issue, you hereby license all content you contribute
to this repository (including but not limited to this issue and all bugs,
commits, pull requests, feature requests, and suggestions) under the
repository's
[LICENSE](https://github.com/holvonix-open/solr-query-io-ts/blob/master/LICENSE).
You also represent and warrant that you have all necessary rights to license the
content as specified in the preceding sentence and that doing so will not
infringe upon any right of any third party nor violate any applicable law or
regulation.**

**Describe the bug** A clear and concise description of what the bug is.
Error importing io-ts package and warning critical dependency.

**To Reproduce** Steps to reproduce the behavior:
1. Install this package
2. Import this package using described in the readme

**Expected behavior** A clear and concise description of what you expected to
happen.
No warning or error happens

**Screenshots** If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/20434351/62875835-ebefbf00-bd4d-11e9-88db-2d208dfd17fe.png)
![image](https://user-images.githubusercontent.com/20434351/62875867-fe69f880-bd4d-11e9-894d-f7d9fdab5498.png)

**Desktop (please complete the following information):**

- OS: [e.g. iOS] Linux Mint
- Browser [e.g. chrome, safari] Google Chrome 
- Version [e.g. 22] 76.0.3809.100

**Smartphone (please complete the following information):**

**Additional context** Add any other context about the problem here.
Perhaps this https://github.com/webpack/webpack/issues/2675#issuecomment-385073386 can help to debug the issue

**Comment by holvonixAdvay** [comment]
Thanks for the report.  However, we don't use webpack, and your report doesn't specify exactly how to reproduce your error.  I just spun up a new node package and things work fine:

```bash
yarn init
yarn add solr-query-io-ts
echo "const x = require('solr-query-io-ts'); console.log(x.Q.L('x'));" > index.js
node index.js
```
works fine.

You are welcome to contribute a fix for webpack if you have one.
